$ErrorActionPreference = 'Stop'
$paths = @(
    'app/Http/Controllers/Api/V1',
    'app/Http/Requests/V1',
    'app/Http/Resources/V1',
    'app/Policies',
    'app/Services',
    'tests/Feature/Api',
    'tests/Support',
    'routes/api_v1.php',
    'config/api.php',
    'config/cors.php',
    'database/migrations/2026_09_11_100000_harden_api_data.php',
    'app/Http/Middleware/RequireSpaSession.php',
    'app/Notifications/VerifyApiEmail.php',
    'app/Models',
    'app/Providers/AppServiceProvider.php',
    'bootstrap/app.php',
    'config/database.php',
    'config/sanctum.php',
    'database/factories/UserFactory.php',
    'routes/api.php',
    'routes/web.php',
    'tests/TestCase.php',
    'app/Notifications/NewOrderNotification.php',
    'app/Http/Controllers/Admin/OrderController.php',
    'app/Http/Controllers/Admin/ProductController.php',
    'app/Http/Controllers/Admin/UserController.php',
    'app/Http/Controllers/Api/AuthController.php',
    'app/Http/Controllers/Api/OrderController.php',
    'app/Http/Controllers/Store/CartController.php',
    'app/Http/Controllers/ProfileController.php',
    'app/Http/Controllers/Auth/RegisteredUserController.php',
    'app/Http/Controllers/Auth/ConfirmablePasswordController.php',
    'app/Http/Controllers/Auth/EmailVerificationNotificationController.php',
    'app/Http/Controllers/Auth/EmailVerificationPromptController.php',
    'app/Http/Controllers/Auth/VerifyEmailController.php',
    'tests/Feature/Auth/AuthenticationTest.php',
    'tests/Feature/Auth/EmailVerificationTest.php',
    'tests/Feature/Auth/RegistrationTest.php'
)
php vendor/bin/pint --test @paths
exit $LASTEXITCODE

